### ISSUE TITLE
BiCV module not correctly break and return an error message when error occurs

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#140] opened 2022-02-10 21:30 UTC
When I tested the BiCV module using the MWE with N = 0

The APEX crash as expected. However, despite SOS being able to capture the error message in the stderr, it fail to produce the usual error message like:
```
ERROR: BiCV (id=640612ca8c5b328e) returns an error.
ERROR: [BiCV]: [0]: Executing script in Singularity returns an error (exitcode=127, stderr=/mnt/mfs/statgen/xqtl_workflow_testing/demo/PEER/APEX_MWE/demo.BiCV.cov.gz.stderr).
The script has been saved to /home/hs3163/.sos/debeff2331eb1a6b/singularity_run_9980.sh. To reproduce the error please run:
singularity exec  /mnt/mfs/statgen/containers/lmm.sif /bin/bash /home/hs3163/.sos/debeff2331eb1a6b/singularity_run_9980.sh
```
But instead think the step is finished just cant find the output, as :
```
INFO: Running BiCV:
INFO: BiCV is completed.
ERROR: [BiCV]: [BiCV]: Output target /mnt/mfs/statgen/xqtl_workflow_testing/demo/PEER/APEX_MWE/demo.BiCV.cov.gz does not exist after the completion of step BiCV
```

To reproduce this behavior, simply run
```
sos run BiCV_factor.ipynb BiCV \
--phenoFile AC.mol_phe.annotated.bed.gz \
--vcfFile demo_chr1.vcf.gz \
--covFile AC.APEX.cov --cwd ./ \
--container apex.sif --name "demo" -N 0  &
```

**Comment by gaow** [comment] 2022-02-18 19:53
can you reproduce it robustly?

**Comment by hsun3163** [comment] 2022-02-18 20:06
> can you reproduce it robustly?

Yes, take the test.sos you made earlier for example:
```
[rename_chr: provides = '{filename}.renamed.vcf']
input: f'{filename}.vcf'
bash: expand = '${ }'
        touch ${_input:n}.renamed.vcf

[qc]
parameter: vcf_files = list
input: vcf_files, group_by = 1
output: f"{_input:n}.log"
bash: expand = True
        bcftools
        ls -lhrt {_input} > {_output}
```

This will produce following result:

```
hs3163@node56:/mnt/mfs/statgen/snuc_pseudo_bulk$ sos run test.sos --vcf_files chr1.vcf chr2.vcf
INFO: Running qc:
/tmp/tmp9fbncbjj.sh: line 1: bcftools: command not found
/tmp/tmpvn855daj.sh: line 1: bcftools: command not found
INFO: qc (index=0) is completed.
INFO: qc (index=1) is completed.
INFO: qc output:   chr1.log chr2.log in 2 groups
INFO: Workflow qc (ID=w6fa1f9a0958556e5) is executed successfully with 1 completed step and 2 completed substeps.
```
while ideally it should break due to after `/tmp/tmp9fbncbjj.sh: line 1: bcftools: command not found`

**Comment by gaow** [comment] 2022-02-18 20:11
I see. If you swap bcftools and the ls command it's going to quit on error. This is a somewhat expected  behavior for `bash` code. As developers of pipelines we must be careful. 

this can be fixed with one of the following:

```
set -e 
bcftools 
ls -lhrt {_input} > {_output}
```

or 

```
bcftools && \
ls -lhrt {_input} > {_output}
```

**Comment by hsun3163** [comment] 2022-02-18 20:13
in this case we should include `set -e` for every cells when more than 1 bash command is run then.

**Comment by gaow** [comment] 2022-02-24 16:13
Close this because it's an SoS discussion not specific to APEX

**Closed by gaow** 2022-02-24 16:13 UTC
Labels: bug, help wanted

**Comment by gaow** [comment] 2022-02-24 23:14
The solution is either to use:

```
run: ...
````
instead of 

```
bash: ..
````

where on Linux (which is the case of our docker) `run` uses `bash -e` . Or, specify this for bash actions:

```
bash: args='-e {filename:q}.
```

I'm fine with both approaches. To ensure good behavior cross platform I would probably go for the 2nd option
